services:
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:15
    restart: unless-stopped
    ports:
      - "${DatabaseSettings__Port}:5432"
    environment:
      POSTGRES_USER: ${DatabaseSettings__Username}
      POSTGRES_PASSWORD: ${DatabaseSettings__Password}
      POSTGRES_DB: ${DatabaseSettings__Database}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: ${PROJECT_NAME}-pgdata
